services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    # depends_on:
    #   - node
    build:
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
    networks:
      - net

networks:
  net: 
    external: {
      name: proxy_dev
    }
    
